#!/bin/bash

echo $(cat <<-EOF
window.config = {
  auth0_domain:"cohesioned.auth0.com",
  auth0_client_id:"${REACT_APP_AUTH0_CLIENT_ID}",
  callback_url:"${REACT_APP_CALLBACK_URL}",
  ga_tracking_id:"${REACT_APP_GA_TRACKING_ID}",
  logout_return_to:"${REACT_APP_LOGOUT_RETURN_TO}"
  stripe_key:"${STRIPE_KEY}"
}
EOF
) > ./build/config.js
